GET http://localhost:3000

###

POST http://localhost:3000/api/signup HTTP/1.1
Content-Type: application/json

{
   "username": "user0",
   "email": "user0@email.com",
   "password": "myPass123"
}

###

POST http://localhost:3000/api/signin HTTP/1.1
Content-Type: application/json

{
   "username": "user0",
   "email": "user0@email.com",
   "password": "myPass123"
}
